version: "2"

services:
  memcached:
    image: memcached:1.5.7
    hostname: memcached
    env_file: .env
    ports:
      - "12211:12211"

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"

  celery_worker_1:
    build: .
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan worker --loglevel INFO
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq

  celery_worker_2:
    build: .
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan worker --loglevel INFO
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq

  celery_worker_3:
    build: .
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan worker --loglevel INFO
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq

  celery_worker_4:
    build: .
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan worker --loglevel INFO
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq

  celery_beat:
    build: .
    env_file: .env
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan beat --max-interval=10 --pidfile= --loglevel INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq

  web:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - memcached
      - rabbitmq
