version: "2"

volumes:
  db-data:
    external: false

services:
  postgres:
    image: postgres:9.4
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  memcached:
    image: memcached:1.5.7
    hostname: memcached
    env_file: .env
    ports:
      - "12211:12211"

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"

  celery_worker:
    build: .
    command: dockerize -wait tcp://postgres:5432 -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan worker --loglevel DEBUG
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq
      - postgres

  celery_beat:
    build: .
    env_file: .env
    command: dockerize -wait tcp://postgres:5432 -wait tcp://rabbitmq:5672 -timeout 60s celery -A samaritan beat --max-interval=10 --pidfile= --loglevel DEBUG
    volumes:
      - .:/usr/src/app
    depends_on:
      - memcached
      - rabbitmq
      - postgres

  web:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - memcached
      - rabbitmq
      - postgres

