# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samaritan', '0022_auto_20190423_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Webhook configuration', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('default_membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samaritan.MembershipType')),
                ('default_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samaritan.ChurchRole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
