# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdayemailgreetingconfiguration',
            old_name='send_greeting',
            new_name='send_emails',
        ),
        migrations.RenameField(
            model_name='birthdayslistconfiguration',
            old_name='send_list',
            new_name='send_emails',
        ),
        migrations.AddField(
            model_name='grouprotationconfiguration',
            name='send_emails',
            field=models.BooleanField(default=False),
        ),
    ]
