# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0002_auto_20171207_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Password Reset Email Configurations', max_length=200)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_message', models.TextField()),
                ('send_email', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
