# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0022_auto_20190423_1835'),
        ('emailservice', '0004_welcomeemailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayemailgreetingconfiguration',
            name='excluded_roles',
            field=models.ManyToManyField(to='samaritan.ChurchRole'),
        ),
    ]
