# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0005_birthdayemailgreetingconfiguration_excluded_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=b'attachments')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
