# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_data_from_legacy_models(apps, schema_editor):
    """Moving existing data from each legacy email configuration to the new email configuration."""
    EmailConfiguration = apps.get_model('emailservice', 'EmailConfiguration')
    WelcomeEmailConfiguration = apps.get_model('emailservice', 'WelcomeEmailConfiguration')
    PasswordResetEmailConfiguration = apps.get_model('emailservice', 'PasswordResetEmailConfiguration')
    BirthdayEmailGreetingConfiguration = apps.get_model('emailservice', 'BirthdayEmailGreetingConfiguration')
    BirthdaysListConfiguration = apps.get_model('emailservice', 'BirthdaysListConfiguration')

    welcome_email = WelcomeEmailConfiguration.objects.all().first()
    passwd_reset = PasswordResetEmailConfiguration.objects.all().first()
    birthday_greeting = BirthdayEmailGreetingConfiguration.objects.all().first()
    birthdays_list = BirthdaysListConfiguration.objects.all().first()

    birthday_list_message = "Please see below the list of church members who had a birthday last month:"

    if welcome_email:
        EmailConfiguration.objects.create(
            type='WELCOME_EMAIL',
            description='Welcome email configuration',
            subject=welcome_email.email_subject,
            message=welcome_email.email_message,
            send_email=welcome_email.send_email,
        )
    if passwd_reset:
        EmailConfiguration.objects.create(
            type='PASSWORD_RESET',
            description='Password reset email configuration',
            subject=passwd_reset.email_subject,
            message=passwd_reset.email_message,
            send_email=passwd_reset.send_email,
        )
    if birthday_greeting:
        EmailConfiguration.objects.create(
            type='BIRTHDAY_GREETING',
            description='Birthday greeting email configuration',
            subject=birthday_greeting.subject,
            message=birthday_greeting.greeting,
            send_email=birthday_greeting.send_emails,
        )
    if birthdays_list:
        EmailConfiguration.objects.create(
            type='BIRTHDAY_LIST',
            description='Birthdays list email configuration',
            subject=birthdays_list.subject,
            scheduled_day=birthdays_list.sending_day,
            message=birthday_list_message,
            send_email=birthdays_list.send_emails,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0022_auto_20190423_1835'),
        ('emailservice', '0007_emailoutbox_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('type', models.CharField(choices=[
                    (b'BIRTHDAY_GREETING', b'BIRTHDAY GREETING'),
                    (b'BIRTHDAY_LIST', b'BIRTHDAY LIST'),
                    (b'PASSWORD_RESET', b'PASSWORD RESET'),
                    (b'WELCOME_EMAIL', b'WELCOME EMAIL')
                ], max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_day', models.IntegerField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('excluded_roles', models.ManyToManyField(
                    related_name='excluded', to='samaritan.ChurchRole', blank=True
                )),
                ('recipient_roles', models.ManyToManyField(
                    related_name='recipient', to='samaritan.ChurchRole', blank=True
                )),
            ],
        ),
        migrations.RunPython(migrate_data_from_legacy_models),
        migrations.RemoveField(
            model_name='birthdayemailgreetingconfiguration',
            name='excluded_roles',
        ),
        migrations.RemoveField(
            model_name='birthdayslistconfiguration',
            name='recipient_roles',
        ),
        migrations.DeleteModel(
            name='GroupRotationConfiguration',
        ),
        migrations.DeleteModel(
            name='PasswordResetEmailConfiguration',
        ),
        migrations.DeleteModel(
            name='WelcomeEmailConfiguration',
        ),
        migrations.DeleteModel(
            name='BirthdayEmailGreetingConfiguration',
        ),
        migrations.DeleteModel(
            name='BirthdaysListConfiguration',
        ),
    ]
