# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0008_auto_20200511_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='type',
            field=models.CharField(choices=[(b'BIRTHDAY_GREETING', b'BIRTHDAY GREETING'), (b'BIRTHDAY_LIST', b'BIRTHDAY LIST'), (b'PASSWORD_RESET', b'PASSWORD RESET'), (b'WEBHOOK_NOTIFICATION', b'WEBHOOK NOTIFICATION'), (b'WELCOME_EMAIL', b'WELCOME EMAIL')], max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
