# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-07 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0009_auto_20200601_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='type',
            field=models.CharField(choices=[(b'BIRTHDAY_GREETING', b'BIRTHDAY GREETING'), (b'BIRTHDAY_LIST', b'BIRTHDAY LIST'), (b'LOGIN_LINK', b'LOGIN LINK'), (b'PASSWORD_RESET', b'PASSWORD RESET'), (b'WEBHOOK_NOTIFICATION', b'WEBHOOK NOTIFICATION'), (b'WELCOME_EMAIL', b'WELCOME EMAIL')], max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
