# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChurchRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('baptismal_date', models.DateField(blank=True)),
                ('is_member', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samaritan.Address')),
            ],
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='member',
            field=models.ManyToManyField(to='samaritan.Member'),
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samaritan.ChurchRole'),
        ),
    ]
