# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchgroup',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='church_role',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='samaritan.ChurchRole'),
        ),
    ]
