# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0002_auto_20160502_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='churchrole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='church_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samaritan.ChurchRole'),
        ),
    ]
