# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0003_auto_20160502_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_baptised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
