# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0004_auto_20160507_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
