# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0007_auto_20160515_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptismal_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
