# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0008_member_baptismal_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samaritan.MembershipType'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
