# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0010_auto_20160517_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_type',
            new_name='membership_type',
        ),
    ]
