# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0012_auto_20160517_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
