# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0017_auto_20160628_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchgroup',
            old_name='member',
            new_name='members',
        ),
    ]
