# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0018_auto_20160628_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gdpr',
            field=models.BooleanField(default=False),
        ),
    ]
