# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0018_auto_20160628_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(verbose_name=b'group number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
