# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0019_member_gdpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samaritan.Address'),
        ),
    ]
