# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0020_auto_20180523_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'profile_image'),
        ),
    ]
