# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0021_auto_20181227_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samaritan.MembershipType'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'images/guest.png', null=True, upload_to=b'profile_images_members'),
        ),
    ]
