# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-11 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samaritan', '0023_auto_20200607_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(b'ARCHIVE_MEMBER', 'ARCHIVE MEMBER'), (b'CREATE_MEMBER', 'CREATE MEMBER'), (b'DELETE_MEMBER', 'DELETE MEMBER'), (b'UNARCHIVE_MEMBER', 'UNARCHIVE MEMBER'), (b'UPDATE_MEMBER', 'UPDATE MEMBER')], max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='samaritan.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
