# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samaritan', '0023_auto_20200607_1428'),
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='samaritan.Member'),
        ),
    ]
