# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_activitylog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[(b'ARCHIVE_MEMBER', 'ARCHIVE MEMBER'), (b'CREATE_MEMBER', 'CREATE MEMBER'), (b'DELETE_MEMBER', 'DELETE MEMBER'), (b'UNARCHIVE_MEMBER', 'UNARCHIVE MEMBER'), (b'UPDATE_MEMBER', 'UPDATE MEMBER')], max_length=100),
        ),
    ]
