# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'images/guest.png', null=True, upload_to=b'profile_images'),
        ),
    ]
