# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190423_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
