# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-08 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_mfacode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'MFA Settings', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
