# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_mfaconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
