# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfacode',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
