"""
@author: Silvian Dragan
@Date: 02/05/2016
@Copyright: Copyright 2016, Samaritan CMA - Published under GNU General Public Licence v3
@Details: https://github.com/Silvian/samaritan

Django settings for samaritan project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from __future__ import absolute_import

import os

from celery.schedules import crontab

# Global settings static variables config
AUTHOR = "Silvian Dragan"
COPYRIGHT = "Copyright {year}, Samaritan CMA (Church Management Assistant)"
LICENCE = "GPLv3"
VERSION = "1.1"
MAINTAINER = "Silvian Dragan"
EMAIL = "silvian.dragan@gmail.com"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = os.getenv('STATIC_ROOT', default='')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', default='a@!wnp8fx8rjm4(kmbjblnxi$$53g$-3_8qdva32eh17yk4c@c')

if 'PRODUCTION' in os.environ:
    DEBUG = False

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    # SECURITY SETTINGS: ensure the below settings are turned on when running with SSL/TLS active
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

ALLOWED_HOSTS = ['*']

# Static files
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # 'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(BASE_DIR, 'static', STATIC_ROOT),
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'axes',
    'api',
    'samaritan',
    'authentication',
    'emailservice',
    'export',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'samaritan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/samaritan/templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'samaritan.wsgi.application'


# Cache configurations
# Memcached standard configurations

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

if 'MEMCACHED_HOST' in os.environ:
    CACHES['default']['LOCATION'] = os.getenv('MEMCACHED_HOST')

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

if 'DATABASE_HOST' in os.environ:
    DATABASES['default']['HOST'] = os.getenv('DATABASE_HOST')
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql_psycopg2'
    DATABASES['default']['NAME'] = os.getenv('DATABASE_NAME')
    DATABASES['default']['USER'] = os.getenv('DATABASE_USER')
    DATABASES['default']['PASSWORD'] = os.getenv('DATABASE_PASSWORD')


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Celery Configurations
# Celery & Broker settings

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', default="amqp://guest:guest@rabbitmq")
CELERY_RESULTS_BACKEND = os.getenv('CELERY_RESULTS_BACKEND', default="amqp://guest:guest@rabbitmq")

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', default='Europe/London')


# Celery cron scheduling

CELERY_BEAT_SCHEDULE = {
    'send_birthday_greeting': {
        'task': 'emailservice.tasks.send_birthday_greeting',
        'schedule': crontab(minute='5', hour='8'),
    },
    'send_birthdays_list': {
        'task': 'emailservice.tasks.send_birthdays_list',
        'schedule': crontab(minute='0', hour='9'),
    },
    'group_rotation_schedule': {
        'task': 'emailservice.tasks.group_rotation_schedule',
        'schedule': crontab(minute='30', hour='0', day_of_week='0'),
    },
    'send_group_schedule_notification': {
        'task': 'emailservice.tasks.send_group_schedule_notification',
        'schedule': crontab(minute='35', hour='9', day_of_week='5'),
    },
}

# Django celery results configurations
CELERY_RESULT_BACKEND = 'django-db'


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/authenticate/login/'

LOGOUT_URL = '/authenticate/login?logout=true'

AXES_LOCKOUT_URL = '/authenticate/login?lockout=true'

REDIRECT_URL = os.getenv('REDIRECT_URL', default='/')


# SMTP settings
# Note that these settings are environment specific

EMAIL_HOST = os.getenv('EMAIL_HOST', default='')
EMAIL_PORT = os.getenv('EMAIL_PORT', default='')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', default=False)
