# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessageConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SMS Message', max_length=50)),
                ('send_message', models.BooleanField(default=False)),
                ('counter', models.PositiveIntegerField()),
                ('quota_remaining', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
