# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessageconfiguration',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsmessageconfiguration',
            name='quota_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
