# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageservice', '0002_auto_20180820_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessageconfiguration',
            name='quota_remaining',
        ),
    ]
