# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageservice', '0003_remove_smsmessageconfiguration_quota_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessageconfiguration',
            name='sender_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
